FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY index.html /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY favicon.png /usr/share/nginx/html/
COPY logo-icon.png /usr/share/nginx/html/
COPY social-share.jpg /usr/share/nginx/html/
